server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


spring:
  application:
    name: picture-backend
    # 数据库连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  # Redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    connect-timeout: 5000
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  #开放更大的文件上传体积
  servlet:
    multipart:
      #max-request-size: 10MB
      max-file-size: 10MB
  # 移除以下配置
  # 空间图片分表
  # shardingsphere:
  #   datasource:
  #     names: picture
  #     picture:
  #       type: com.zaxxer.hikari.HikariDataSource
  #       driver-class-name: com.mysql.cj.jdbc.Driver
  #       url: jdbc:mysql://localhost:3306/picture
  #       username: root
  #       password: 123456
  #   rules:
  #     sharding:
  #       tables:
  #         picture:
  #           actual-data-nodes: picture.picture  # 动态分表
  #           table-strategy:
  #             standard:
  #               sharding-column: spaceId
  #               sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
  #       sharding-algorithms:
  #         picture_sharding_algorithm:
  #           type: CLASS_BASED
  #           props:
  #             strategy: standard
  #             algorithmClassName: com.xcw.picturebackend.manager.sharding.PictureShardingAlgorithm
  #   props:
  #     sql-show: true

#mybatis-plus配置
mybatis-plus:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: false
    # 仅在开发环境下打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除配置
  global-config:
    # 开启sql执行分析插件(阻止全表更新与删除)
    enable-sql-runner: true
    db-config:
      # 逻辑删除字段
      logic-delete-field: isDelete
      # 逻辑未删除值(默认为0)
      logic-not-delete-value: 0
      # 逻辑删除值(默认为1)
      logic-delete-value: 1

#接口文档Knife4j配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xcw.picturebackend.controller